# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  sandbox:
    cmds:
      - uv run python -m notebook
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
